import type { Metadata } from 'next'
import Script from 'next/script'
import manifest from '../../public-typescript/manifest.json'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
      <Script src={manifest.istanbul} />
    </html>
  )
}
